- name: Secure my Network estate
  hosts: network
  connection: local
  tasks:
   - name: Create Management ACL
     ios_config:
      lines:
       - 10 permit ip host 1.1.1.1 any log
       - 20 permit ip host 2.2.2.2 any log
       - 30 permit ip host 3.3.3.3 any log
       - 40 permit ip host 4.4.4.4 any log
       - 50 permit ip host 5.5.5.5 any log
      parents: ip access-list extended test
   - name: Harden VTY lines
     ios_config:
       parents: line vty 0 15
       lines:
         - exec-timeout 15
         - transport input ssh
         - access mgmnt in
   - name: Apply ACL to interface
     ios_config:
      lines:
       -  ip access-group test in
      parents: "interface GigabitEthernet2"
