---
- name: Check if a CVE is patched
  hosts: linux
  tasks:

# Survey delivers the CVE to check..
# Runs on linux group - skips everything but debian.
  - name: Check if CVE is present - Debian only
    shell: debsecan --suite=sid --only-fixed |grep "{{ CVE }}"
    when: ansible_os_family == "Debian"
    register: CVE_is_present

  - debug: var=CVE_is_present
