---
- name: Check if a CVE is patched
  hosts: linux
  tasks:
  - name: Check if CVE is present - Debian only
    shell: debsecan --suite=sid --only-fixed |grep "{{ CVE }}"
    when: ansible_os_family == "Debian"
    register: CVE_is_present
  - debug: var=CVE_is_present
