---
- name: Check if a CVE is patched
  hosts: linux
  tasks:

# Survey delivers the CVE to check..
# Runs on linux group - skips everything but debian.
  - name: Check if CVE is present - Debian only
    shell: debsecan --suite=sid --only-fixed |grep "{{ CVE }}"
    when: ansible_os_family == "Debian"
    register: CVE_is_present

#  - debug: var=CVE_is_present


# Set default value if we didnt get results.
  - set_fact:
      found: |
        {{ CVE_is_present.stdout.split()[:-1] or "notfound" }}
    when: ansible_os_family == "Debian"

# Check value within 'found' and compare it against KB article that was
# fed in via ansible tower survey.
  - name: CVE is Installed
    debug:
      msg: var="{{ CVE }} is installed"
    when: found[2] != "notfound" and ansible_os_family == "Debian"

  - name: CVE is not installed
    debug:
      msg: var="{{ KB }} is not installed"
    when: found[2] == "notfound" and ansible_os_family == "Debian"
