---
- name: Check if KB is installed
  hosts: windows
  vars:
    ansible_port: 5986
    ansible_connection: winrm
    ansible_winrm_transport: basic
    ansible_ssh_port: 5986
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_kerberos_delegation: yes
  tasks:
  - name: Is this KB Installed?
    win_shell: get-hotfix | out-string -stream | select-string "{{ KB }}"
    register: WIN_CVE

  - debug:
      msg: "test-msg"
  - debug: 
      msg:"{{ WIN_CVE.stdout_lines |
              map('regex_findall','KB*') | 
              map('join') | list }}"

