---
- name: Check if a CVE is patched
  hosts: linux
  tasks:
  - name: Check if CVE is patched Ubuntu
    shell: debsecan --suite=sid --only-fixed |grep "{{ CVE }}"
    when: ansible_os_family == "Debian"
    register: Ubuntu_CVE
  - debug: var=Ubuntu_CVE
