---
- name: Get Device Facts
  hosts: network 
  roles:
  - Juniper.junos
  connection: local
  gather_facts: no

  tasks:

  - name: Verifying NETCONF
    wait_for: host={{ ansible_ssh_host }}  port=830      # variable defined in inventory file

  - name: Retrieve information from devices running Junos OS
    junos_facts:
    register: junos

  - name: version
    debug: msg="{{ junos.ansible_facts.ansible_net_version }}"

  - name: De-activate the motd banner
    junos_banner:
      banner: motd
      state: absent

  - name: Activate and configure the login banner
    junos_banner:
      banner: login
      text: "{{ lookup('file', 'raw_banner.cfg') }}" 
      state: present
